# Use postgres/example user/password credentials
version: '3.1'

services:
    rabbit:
        image: rabbitmq:3
        ports:
             - 5672:5672
    db:
        image: postgres
        environment:
                    POSTGRES_PASSWORD: example
                    POSTGRES_USER: postgres
                    POSTGRES_DB: postgres
        ports:
             - 5432:5432
    adminer:
        image: adminer
        ports:
            - 8080:8080
